/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package podmamanagement;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTabbedPane;
import javax.swing.plaf.basic.BasicTabbedPaneUI;

/**
 *
 * @author millat
 */
public class ClientDetailFrame extends javax.swing.JFrame {
    
    
    /**
     * Creates new form ClientDetailFrame
     */
    public ClientDetailFrame() {
        initComponents();
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        CTabbedPaneDetail = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        jLabel79 = new javax.swing.JLabel();
        jLabel80 = new javax.swing.JLabel();
        jLabel81 = new javax.swing.JLabel();
        jLabel82 = new javax.swing.JLabel();
        jLabel83 = new javax.swing.JLabel();
        jLabel84 = new javax.swing.JLabel();
        jLabel85 = new javax.swing.JLabel();
        jLabel87 = new javax.swing.JLabel();
        jLabel88 = new javax.swing.JLabel();
        jLabel89 = new javax.swing.JLabel();
        jLabel90 = new javax.swing.JLabel();
        jLabel91 = new javax.swing.JLabel();
        ClientAddMessage1 = new javax.swing.JLabel();
        A_Name = new javax.swing.JLabel();
        jLabel94 = new javax.swing.JLabel();
        A_age = new javax.swing.JLabel();
        A_Birth = new javax.swing.JLabel();
        A_fath = new javax.swing.JLabel();
        A_moth = new javax.swing.JLabel();
        jLabel99 = new javax.swing.JLabel();
        A_perma_add = new javax.swing.JLabel();
        A_marital = new javax.swing.JLabel();
        A_occupa = new javax.swing.JLabel();
        A_pnone = new javax.swing.JLabel();
        R1_name = new javax.swing.JLabel();
        R1_fath = new javax.swing.JLabel();
        R1_presadd = new javax.swing.JLabel();
        R1_perma_add = new javax.swing.JLabel();
        R1_pnone = new javax.swing.JLabel();
        R1_birth = new javax.swing.JLabel();
        R1_income = new javax.swing.JLabel();
        R1_occupation = new javax.swing.JLabel();
        R2_name = new javax.swing.JLabel();
        R2_fath = new javax.swing.JLabel();
        R2_pres_add = new javax.swing.JLabel();
        R2_perma_add = new javax.swing.JLabel();
        R2_phne = new javax.swing.JLabel();
        R2_Birth = new javax.swing.JLabel();
        R2_occupation = new javax.swing.JLabel();
        R2_income = new javax.swing.JLabel();
        A_sex = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        A_id = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        tfRef2Phone = new javax.swing.JTextField();
        tfRef1Occupation = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        tfRef1Birth = new javax.swing.JTextField();
        cbapplicantmaritalcondition = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        tfRef1Phone = new javax.swing.JTextField();
        cbapplicantsex = new javax.swing.JComboBox();
        jLabel21 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        tfapplicantfatherHusband = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        tfRef2PermenantAddress = new javax.swing.JTextField();
        tfapplicantbirth = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        tfapplicantOccupation = new javax.swing.JTextField();
        tfRef2Income = new javax.swing.JTextField();
        tfapplicantname = new javax.swing.JTextField();
        tfApplicantId = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        ckbRef2 = new javax.swing.JCheckBox();
        tfRef1PresentAddress = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        tfRef2FatherHusbandName = new javax.swing.JTextField();
        tfRef1FatherHusbandName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        tfRef2Name = new javax.swing.JTextField();
        tfRef2Occupation = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ckbapplicant = new javax.swing.JCheckBox();
        tfapplicantmother = new javax.swing.JTextField();
        ClientAddMessage = new javax.swing.JLabel();
        tfapplicantPhone = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        tfapplicantage = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfRef2Birth = new javax.swing.JTextField();
        tfRef1PermenantAddress = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        tfapplicantpermenantaddress = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        ckbRef1 = new javax.swing.JCheckBox();
        jLabel27 = new javax.swing.JLabel();
        tfRef2PresentAddress = new javax.swing.JTextField();
        tfapplicantpresentaddress = new javax.swing.JTextField();
        tfRef1Name = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        tfRef1Income = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        BClientUpdate = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Update Client Info");

        jPanel2.setAutoscrolls(true);

        jLabel61.setText("Applicant Name:");

        jLabel62.setText("Age:");

        jLabel63.setText("Mother Name:");

        jLabel64.setText("Present Address:");

        jLabel65.setText("Occupation:");

        jLabel66.setFont(new java.awt.Font("DejaVu Sans", 3, 18)); // NOI18N
        jLabel66.setForeground(new java.awt.Color(243, 83, 28));
        jLabel66.setText("Client Details");

        jLabel67.setText("Permenant Address:");

        jLabel68.setText("Marital Condition:");

        jLabel69.setText("Phone No.:");

        jLabel70.setText("References 1");

        jLabel71.setText("Name:");

        jLabel72.setText("Present Address:");

        jLabel73.setText("Permenant Address:");

        jLabel74.setText("Phone Number:");

        jLabel75.setText("Date of Birth(dd/mm/yy):");

        jLabel76.setText("Occupation:");

        jLabel77.setText("Monthly Income:");

        jLabel78.setText("Monthly Income:");

        jLabel79.setText("References 2");

        jLabel80.setText("Name:");

        jLabel81.setText("Present Address:");

        jLabel82.setText("Permenant Address:");

        jLabel83.setText("Phone Number:");

        jLabel84.setText("Date of Birth(dd/mm/yy):");

        jLabel85.setText("Occupation:");

        jLabel87.setText("Sex:");

        jLabel88.setText("Date of Birth(dd/mm/yy):");

        jLabel89.setText("Father/Husband Name:");

        jLabel90.setText("Father/Husband Name:");

        jLabel91.setText("Father/Husband Name:");

        A_Name.setText("lappName");

        A_age.setText("A Age");

        A_Birth.setText("A birth");

        A_fath.setText("A fath/hus");

        A_moth.setText("A mother");

        jLabel99.setText("A present add");

        A_perma_add.setText("A perma add");

        A_marital.setText("A Marital");

        A_occupa.setText("A occupation ");

        A_pnone.setText("A phone");

        R1_name.setText("R1 name");

        R1_fath.setText("R1 fath");

        R1_presadd.setText("R1 present add");

        R1_perma_add.setText("R1 permanent add");

        R1_pnone.setText("R1 pnone");

        R1_birth.setText("R1 birth");

        R1_income.setText("R1 income");

        R1_occupation.setText("R1 occupation");

        R2_name.setText("R2 name");

        R2_fath.setText("R2 fath");

        R2_pres_add.setText("R2 pres add");

        R2_perma_add.setText("R2 perma add");

        R2_phne.setText("R2 pnone");

        R2_Birth.setText("R2 birth");

        R2_occupation.setText("R2 occupation");

        R2_income.setText("R2 income");

        A_sex.setText("A sex");

        jLabel7.setText("Applicant id : ");

        A_id.setText("A id");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel85, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel84, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel81, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel80, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel91, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel83, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel78, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(ClientAddMessage1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel61, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel62, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel88, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                            .addComponent(jLabel89, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel64, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel87)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(108, 108, 108)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(A_age, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel94))
                            .addComponent(A_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(A_sex, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(A_Birth, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(A_fath, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(A_id, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(664, 664, 664))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel68, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                            .addComponent(jLabel65, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(A_moth, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(A_pnone, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(A_marital, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE)
                                .addComponent(A_occupa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel99, javax.swing.GroupLayout.PREFERRED_SIZE, 688, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(A_perma_add, javax.swing.GroupLayout.PREFERRED_SIZE, 688, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(478, 478, 478))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel69, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel90, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel75, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel77, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(40, 40, 40)
                                    .addComponent(R1_income, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel71, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(40, 40, 40)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(R1_fath, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(R1_name, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
                                        .addComponent(R1_presadd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addComponent(jLabel72, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel73, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(81, 81, 81)
                                    .addComponent(R1_perma_add, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel74, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel76, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(40, 40, 40)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(R1_pnone, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(R1_birth, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(R1_occupation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addComponent(jLabel79)
                                .addComponent(jLabel70)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel82, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(86, 86, 86)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(R2_perma_add, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(R2_phne, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(R2_Birth, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(R2_income, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE)
                                            .addComponent(R2_occupation, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(249, 249, 249)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(R2_fath, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(R2_pres_add, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(R2_name, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel63, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel67, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(442, 442, 442)
                        .addComponent(jLabel66, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel66, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(A_id, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel61)
                    .addComponent(A_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel62, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel94)
                    .addComponent(A_age))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel87)
                    .addComponent(A_sex))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel88, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(A_Birth))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel89, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(A_fath))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel63, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(A_moth))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel64, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel99))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel67, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(A_perma_add)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel68, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(A_marital))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel65, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(A_occupa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel69, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(A_pnone))
                .addGap(62, 62, 62)
                .addComponent(jLabel70)
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel71, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(R1_name))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel90, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(R1_fath))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel72, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(R1_presadd))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel73, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(R1_perma_add))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel74, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(R1_pnone)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel75, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(R1_birth))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel76, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(R1_occupation))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel77, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(R1_income))
                .addGap(37, 37, 37)
                .addComponent(jLabel79)
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel80, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(R2_name))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel91, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(R2_fath))
                .addGap(18, 103, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel81, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(R2_pres_add))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(R2_perma_add)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(R2_phne)
                            .addComponent(jLabel83, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(R2_Birth)
                            .addComponent(jLabel84, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel85, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(R2_occupation))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel78, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(R2_income))
                        .addGap(36, 36, 36)
                        .addComponent(ClientAddMessage1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel82, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(97, Short.MAX_VALUE))
        );

        CTabbedPaneDetail.addTab("Client Full details", jPanel2);

        jLabel9.setFont(new java.awt.Font("DejaVu Sans", 3, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(243, 83, 28));
        jLabel9.setText("Update info");

        jLabel18.setForeground(new java.awt.Color(237, 30, 22));
        jLabel18.setText("Permenant Address:");

        cbapplicantmaritalcondition.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Single", "Married", " " }));

        jLabel8.setText("Marital Condition:");

        cbapplicantsex.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female", " " }));

        jLabel21.setText("Occupation:");

        jLabel33.setText("Sex:");

        jLabel20.setText("Date of Birth(dd/mm/yy):");

        jLabel36.setText("Father/Husband Name:");

        jLabel32.setText("Signature:");

        jLabel35.setText("Father/Husband Name:");

        jLabel30.setText("Occupation:");

        jLabel6.setText("Occupation:");

        jLabel37.setText("Father/Husband Name:");

        tfapplicantOccupation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfapplicantOccupationActionPerformed(evt);
            }
        });

        jLabel26.setText("Present Address:");

        ckbRef2.setText("Same as Present Address");

        jLabel23.setText("Monthly Income:");

        jLabel17.setText("Present Address:");

        jLabel29.setText("Date of Birth(dd/mm/yy):");

        jLabel2.setText("Age:");

        jLabel5.setText("Present Address:");

        jLabel19.setForeground(new java.awt.Color(239, 31, 7));
        jLabel19.setText("Phone Number:");

        jLabel25.setForeground(new java.awt.Color(233, 54, 22));
        jLabel25.setText("Name:");

        jLabel22.setText("Monthly Income:");

        jLabel4.setText("Mother Name:");

        ckbapplicant.setText("Same as present address:");

        tfapplicantmother.setText(" ");

        tfapplicantPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfapplicantPhoneActionPerformed(evt);
            }
        });

        jLabel12.setForeground(new java.awt.Color(232, 54, 23));
        jLabel12.setText("Phone No.:");

        jLabel15.setText("References 1");

        jLabel3.setForeground(new java.awt.Color(232, 15, 15));
        jLabel3.setText("Permenant Address:");

        jLabel16.setForeground(new java.awt.Color(236, 44, 20));
        jLabel16.setText("Name:");

        jLabel24.setText("References 2");

        jLabel34.setText("Date of Birth(dd/mm/yy):");

        ckbRef1.setText("Same as Present Address");
        ckbRef1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbRef1ActionPerformed(evt);
            }
        });

        jLabel27.setForeground(new java.awt.Color(255, 27, 0));
        jLabel27.setText("Permenant Address:");

        jLabel1.setForeground(new java.awt.Color(242, 25, 25));
        jLabel1.setText("Applicant Name:");

        jLabel28.setForeground(new java.awt.Color(240, 62, 20));
        jLabel28.setText("Phone Number:");

        jLabel31.setText("Picture:");

        jLabel38.setForeground(new java.awt.Color(232, 27, 27));
        jLabel38.setText("ID : ");

        BClientUpdate.setText("Update");
        BClientUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BClientUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(557, 557, 557)
                .addComponent(BClientUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(643, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(170, 170, 170)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(218, 218, 218)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel24)
                                .addComponent(jLabel15)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel4)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3)
                                .addComponent(jLabel5)
                                .addComponent(ckbapplicant)
                                .addComponent(jLabel8)
                                .addComponent(jLabel6)
                                .addComponent(jLabel12)
                                .addComponent(jLabel16)
                                .addComponent(jLabel17)
                                .addComponent(jLabel18)
                                .addComponent(jLabel19)
                                .addComponent(jLabel20)
                                .addComponent(jLabel21)
                                .addComponent(jLabel22)
                                .addComponent(ckbRef1)
                                .addComponent(jLabel33)
                                .addComponent(jLabel34)
                                .addComponent(jLabel35)
                                .addComponent(jLabel36))
                            .addGap(45, 45, 45)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cbapplicantsex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(tfapplicantbirth, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tfapplicantname, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tfapplicantage, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tfapplicantfatherHusband, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tfapplicantmother, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tfapplicantpresentaddress, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tfapplicantpermenantaddress, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cbapplicantmaritalcondition, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tfapplicantOccupation, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tfapplicantPhone)
                                            .addComponent(tfRef1Name, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tfRef1FatherHusbandName, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tfRef1PresentAddress, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tfRef1PermenantAddress, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tfRef1Phone, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tfRef1Birth, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tfRef1Occupation, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tfRef1Income, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(60, 60, 60)
                                            .addComponent(jLabel32)
                                            .addGap(178, 178, 178)
                                            .addComponent(jLabel31))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(96, 96, 96)
                                            .addComponent(jLabel38)
                                            .addGap(27, 27, 27)
                                            .addComponent(tfApplicantId, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel25)
                                .addComponent(jLabel26)
                                .addComponent(jLabel27)
                                .addComponent(jLabel28)
                                .addComponent(jLabel29)
                                .addComponent(jLabel30)
                                .addComponent(jLabel23)
                                .addComponent(ckbRef2)
                                .addComponent(jLabel37))
                            .addGap(45, 45, 45)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tfRef2FatherHusbandName)
                                .addComponent(tfRef2PresentAddress)
                                .addComponent(tfRef2PermenantAddress)
                                .addComponent(tfRef2Phone)
                                .addComponent(tfRef2Birth)
                                .addComponent(tfRef2Occupation)
                                .addComponent(tfRef2Income)
                                .addComponent(tfRef2Name, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ClientAddMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(170, 170, 170)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(1307, Short.MAX_VALUE)
                .addComponent(BClientUpdate)
                .addGap(47, 47, 47))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(29, 29, 29)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(tfapplicantname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel38)
                        .addComponent(tfApplicantId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(12, 12, 12)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfapplicantage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2))
                    .addGap(8, 8, 8)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel33)
                        .addComponent(cbapplicantsex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel34)
                        .addComponent(tfapplicantbirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfapplicantfatherHusband, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel35))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfapplicantmother, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfapplicantpresentaddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(ckbapplicant)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3)
                                        .addComponent(tfapplicantpermenantaddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel8)
                                        .addComponent(cbapplicantmaritalcondition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel6)
                                        .addComponent(tfapplicantOccupation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel12)
                                        .addComponent(tfapplicantPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(35, 35, 35))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel31)
                                    .addGap(146, 146, 146)))
                            .addComponent(jLabel15)
                            .addGap(28, 28, 28)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel16)
                                .addComponent(tfRef1Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(tfRef1FatherHusbandName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel36))
                            .addGap(18, 18, 18)
                            .addComponent(jLabel17))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel32)
                            .addGap(241, 241, 241)
                            .addComponent(tfRef1PresentAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(ckbRef1)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel18)
                        .addComponent(tfRef1PermenantAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel19)
                        .addComponent(tfRef1Phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel20)
                        .addComponent(tfRef1Birth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel21)
                        .addComponent(tfRef1Occupation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfRef1Income, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel22))
                    .addGap(44, 44, 44)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel24)
                            .addGap(28, 28, 28)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel25)
                                .addComponent(tfRef2Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(tfRef2FatherHusbandName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel37))
                            .addGap(18, 18, 18)
                            .addComponent(jLabel26))
                        .addComponent(tfRef2PresentAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(ckbRef2)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel27)
                        .addComponent(tfRef2PermenantAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel28)
                        .addComponent(tfRef2Phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel29)
                        .addComponent(tfRef2Birth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel30)
                        .addComponent(tfRef2Occupation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfRef2Income, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel23))
                    .addGap(27, 27, 27)
                    .addComponent(ClientAddMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(230, Short.MAX_VALUE)))
        );

        CTabbedPaneDetail.addTab("Update Client info", jPanel1);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Item Name", "Total Price", "Total Installments", "Remaining Installments", "Money Given"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Installment No", "Price", "Given Date"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 846, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(249, 249, 249)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(530, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1021, Short.MAX_VALUE))
        );

        CTabbedPaneDetail.addTab("Account Info", jPanel3);

        jScrollPane1.setViewportView(CTabbedPaneDetail);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1068, Short.MAX_VALUE)
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 679, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfapplicantOccupationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfapplicantOccupationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfapplicantOccupationActionPerformed

    private void tfapplicantPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfapplicantPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfapplicantPhoneActionPerformed

    private void ckbRef1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbRef1ActionPerformed

    }//GEN-LAST:event_ckbRef1ActionPerformed

    private void BClientUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BClientUpdateActionPerformed
        try {
            String  myDriver = "org.gjt.mm.mysql.Driver";
            String myUrl = "jdbc:mysql://localhost:3306/RudoDatabase";
            Class.forName(myDriver);
            Connection conn = DriverManager.getConnection(myUrl,"test","test");
            String UappId = tfApplicantId.getText();
            String UAppName = tfapplicantname.getText();
            String UAppAge = tfapplicantage.getText();
            String UappSex = cbapplicantsex.getSelectedItem().toString();
            String UappBirth = tfapplicantbirth.getText();
            String UappFath = tfapplicantfatherHusband.getText();
            String UappMoth = tfapplicantmother.getText();
            String UappPresentAdd = tfapplicantpresentaddress.getText();
            String UappPermaAdd = tfapplicantpermenantaddress.getText();
            String UappMarital = cbapplicantmaritalcondition.getSelectedItem().toString();
            String UappOccupa = tfapplicantOccupation.getText();
            String UappPhone = tfapplicantPhone.getText();
            
            String Uref1Name = tfRef1Name.getText();
            String Uref1Fath = tfRef1FatherHusbandName.getText();
            String Uref1PresntAdd = tfRef1PresentAddress.getText();
            String Uref1PermaAdd = tfRef1PermenantAddress.getText();
            String Uref1Phone = tfRef1Phone.getText();
            String uref1Birth = tfRef1Birth.getText();
            String Uref1Occupa = tfRef1Occupation.getText();
            String Uref1Income = tfRef1Income.getText();
            
            String Uref2Name = tfRef2Name.getText();
            String Uref2Fath = tfRef2FatherHusbandName.getText();
            String Uref2PresntAdd = tfRef2PresentAddress.getText();
            String Uref2PermaAdd = tfRef2PermenantAddress.getText();
            String Uref2Phone = tfRef2Phone.getText();
            String uref2Birth = tfRef2Birth.getText();
            String Uref2Occupa = tfRef2Occupation.getText();
            String Uref2Income = tfRef2Income.getText();
            
            String Upquery = "update clientinfo set id = '"+UappId+"',ApplicantName= '"+UAppName+"',ApplicantAge = '"+UAppAge+"',"
                    + "ApplicantSex = '"+UappSex+"',ApplicantBirth = '"+UappBirth+"',ApplicantFatherHusband = '"+UappFath+"',"
                    + "ApplicantMotherName = '"+UappMoth+"',ApplicantPresentAddress = '"+UappPresentAdd+"',ApplicantPermenantAddress = '"+UappPermaAdd+"',"
                    + "ApplicantMarital = '"+UappMarital+"',ApplicantOccupation = '"+UappOccupa+"',ApplicantPhone = '"+UappPhone+"',"
                    + "Ref1Name = '"+Uref1Name+"',Ref1Father = '"+Uref1Fath+"',Ref1PresentAddress = '"+Uref1PresntAdd+"',"
                    + "Ref1PermenantAddress = '"+Uref1PermaAdd+"',Ref1Phone = '"+Uref1Phone+"',Ref1Birth = '"+uref1Birth+"',"
                    + "Ref1Occupation = '"+Uref1Occupa+"',Ref1Income = '"+Uref1Income+"',Ref2Name = '"+Uref2Name+"',Ref2Father = '"+Uref2Fath+"',Ref2PresentAddress = '"+Uref2PresntAdd+"',"
                    + "Ref2PermenantAddress = '"+Uref2PermaAdd+"',Ref2Phone = '"+Uref2Phone+"',Ref2Birth = '"+uref2Birth+"',"
                    + "Ref2Occupation = '"+Uref2Occupa+"',Ref2Income = '"+Uref2Income+"' where id = '"+UappId+"'";
            
            PreparedStatement preparedStmnt = conn.prepareStatement(Upquery);
            
            // Checking is there any field empty..... which are must to be fill up
            if(tfApplicantId.getText().isEmpty() || tfapplicantname.getText().isEmpty() || tfapplicantPhone.getText().isEmpty()
                         || tfapplicantpermenantaddress.getText().isEmpty() ||tfRef1Name.getText().isEmpty() || tfRef1Phone.getText().isEmpty()
                         || tfRef1PermenantAddress.getText().isEmpty()||tfRef2Name.getText().isEmpty() || tfRef2Phone.getText().isEmpty()
                         || tfRef2PermenantAddress.getText().isEmpty())
                         {
                             JOptionPane.showMessageDialog(null, "Red marked field should be fill up.");
                         }else{
                            preparedStmnt.execute();
                            conn.close();
                            JOptionPane.showMessageDialog(null, "Updated");
                            }
            
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_BClientUpdateActionPerformed

    public void ClientInfo(String Clientid){
        
         
        try {
            A_id.setText(Clientid.toString());
            String  myDriver = "org.gjt.mm.mysql.Driver";
            String myUrl = "jdbc:mysql://localhost:3306/RudoDatabase";
            Class.forName(myDriver);
            Connection conn = DriverManager.getConnection(myUrl,"test","test");
            String search = Clientid.toString();
            String uquery = "SELECT * FROM clientinfo WHERE id = '"+search+"'";
            PreparedStatement preparedStmnt = conn.prepareStatement(uquery);
            ResultSet result = preparedStmnt.executeQuery();
            while(result.next()){
                System.out.println(result.getString("ApplicantName"));
                //Client Detail publish ......
                A_Name.setText(result.getString("ApplicantName"));  
                A_age.setText((result.getString("ApplicantAge")));
                A_sex.setText((result.getString("ApplicantSex")));
                A_Birth.setText((result.getString("ApplicantBirth")));
                A_fath.setText((result.getString("ApplicantFatherHusband")));
                A_moth.setText((result.getString("ApplicantMotherName")));
                jLabel99.setText((result.getString("ApplicantPresentAddress")));
                A_perma_add.setText((result.getString("ApplicantPermenantAddress")));
                A_marital.setText((result.getString("ApplicantMarital")));
                A_occupa.setText((result.getString("ApplicantOccupation")));
                A_pnone.setText((result.getString("ApplicantPhone")));
                
                R1_name.setText((result.getString("Ref1Name")));
                R1_fath.setText((result.getString("Ref1Father")));
                R1_presadd.setText((result.getString("Ref1PresentAddress")));
                R1_perma_add.setText((result.getString("Ref1PermenantAddress")));
                R1_pnone.setText((result.getString("Ref1Phone")));
                R1_birth.setText((result.getString("Ref1Birth")));
                R1_occupation.setText((result.getString("Ref1Occupation")));
                R1_income.setText((result.getString("Ref1Income")));
                
                R2_name.setText((result.getString("Ref2Name")));
                R2_fath.setText((result.getString("Ref2Father")));
                R2_pres_add.setText((result.getString("Ref2PresentAddress")));
                R2_perma_add.setText((result.getString("Ref2PermenantAddress")));
                R2_phne.setText((result.getString("Ref2Phone")));
                R2_Birth.setText((result.getString("Ref2Birth")));
                R2_occupation.setText((result.getString("Ref2Occupation")));
                R2_income.setText((result.getString("Ref2Income")));
                
                //Update Client Detail publish .........
                tfApplicantId.setText(result.getString("id"));
                tfapplicantname.setText(result.getString("ApplicantName"));  
                tfapplicantage.setText((result.getString("ApplicantAge")));
                //tfappl.setText((result.getString("ApplicantSex")));
                
                tfapplicantbirth.setText((result.getString("ApplicantBirth")));
                tfapplicantfatherHusband.setText((result.getString("ApplicantFatherHusband")));
                tfapplicantmother.setText((result.getString("ApplicantMotherName")));
                tfapplicantpresentaddress.setText((result.getString("ApplicantPresentAddress")));
                tfapplicantpermenantaddress.setText((result.getString("ApplicantPermenantAddress")));
               // tfapplic.setText((result.getString("ApplicantMarital")));
                tfapplicantOccupation.setText((result.getString("ApplicantOccupation")));
                tfapplicantPhone.setText((result.getString("ApplicantPhone")));
                
                tfRef1Name.setText((result.getString("Ref1Name")));
                tfRef1FatherHusbandName.setText((result.getString("Ref1Father")));
                tfRef1PresentAddress.setText((result.getString("Ref1PresentAddress")));
                tfRef1PermenantAddress.setText((result.getString("Ref1PermenantAddress")));
                tfRef1Phone.setText((result.getString("Ref1Phone")));
                tfRef1Birth.setText((result.getString("Ref1Birth")));
                tfRef1Occupation.setText((result.getString("Ref1Occupation")));
                tfRef1Income.setText((result.getString("Ref1Income")));
                
                tfRef2Name.setText((result.getString("Ref2Name")));
                tfRef2FatherHusbandName.setText((result.getString("Ref2Father")));
                tfRef2PresentAddress.setText((result.getString("Ref2PresentAddress")));
                tfRef2PermenantAddress.setText((result.getString("Ref2PermenantAddress")));
                tfRef2Phone.setText((result.getString("Ref2Phone")));
                tfRef2Birth.setText((result.getString("Ref2Birth")));
                tfRef2Occupation.setText((result.getString("Ref2Occupation")));
                tfRef2Income.setText((result.getString("Ref2Income")));
                
            }
            
        } catch (Exception ex) {
            System.err.println("Got Exception !");
            System.err.println("The Exception is "+ex);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientDetailFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientDetailFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientDetailFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientDetailFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientDetailFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel A_Birth;
    private javax.swing.JLabel A_Name;
    private javax.swing.JLabel A_age;
    private javax.swing.JLabel A_fath;
    private javax.swing.JLabel A_id;
    private javax.swing.JLabel A_marital;
    private javax.swing.JLabel A_moth;
    private javax.swing.JLabel A_occupa;
    private javax.swing.JLabel A_perma_add;
    private javax.swing.JLabel A_pnone;
    private javax.swing.JLabel A_sex;
    private javax.swing.JButton BClientUpdate;
    private javax.swing.JTabbedPane CTabbedPaneDetail;
    private javax.swing.JLabel ClientAddMessage;
    private javax.swing.JLabel ClientAddMessage1;
    private javax.swing.JLabel R1_birth;
    private javax.swing.JLabel R1_fath;
    private javax.swing.JLabel R1_income;
    private javax.swing.JLabel R1_name;
    private javax.swing.JLabel R1_occupation;
    private javax.swing.JLabel R1_perma_add;
    private javax.swing.JLabel R1_pnone;
    private javax.swing.JLabel R1_presadd;
    private javax.swing.JLabel R2_Birth;
    private javax.swing.JLabel R2_fath;
    private javax.swing.JLabel R2_income;
    private javax.swing.JLabel R2_name;
    private javax.swing.JLabel R2_occupation;
    private javax.swing.JLabel R2_perma_add;
    private javax.swing.JLabel R2_phne;
    private javax.swing.JLabel R2_pres_add;
    private javax.swing.JComboBox cbapplicantmaritalcondition;
    private javax.swing.JComboBox cbapplicantsex;
    private javax.swing.JCheckBox ckbRef1;
    private javax.swing.JCheckBox ckbRef2;
    private javax.swing.JCheckBox ckbapplicant;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JLabel jLabel89;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel90;
    private javax.swing.JLabel jLabel91;
    private javax.swing.JLabel jLabel94;
    private javax.swing.JLabel jLabel99;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField tfApplicantId;
    private javax.swing.JTextField tfRef1Birth;
    private javax.swing.JTextField tfRef1FatherHusbandName;
    private javax.swing.JTextField tfRef1Income;
    private javax.swing.JTextField tfRef1Name;
    private javax.swing.JTextField tfRef1Occupation;
    private javax.swing.JTextField tfRef1PermenantAddress;
    private javax.swing.JTextField tfRef1Phone;
    private javax.swing.JTextField tfRef1PresentAddress;
    private javax.swing.JTextField tfRef2Birth;
    private javax.swing.JTextField tfRef2FatherHusbandName;
    private javax.swing.JTextField tfRef2Income;
    private javax.swing.JTextField tfRef2Name;
    private javax.swing.JTextField tfRef2Occupation;
    private javax.swing.JTextField tfRef2PermenantAddress;
    private javax.swing.JTextField tfRef2Phone;
    private javax.swing.JTextField tfRef2PresentAddress;
    private javax.swing.JTextField tfapplicantOccupation;
    private javax.swing.JTextField tfapplicantPhone;
    private javax.swing.JTextField tfapplicantage;
    private javax.swing.JTextField tfapplicantbirth;
    private javax.swing.JTextField tfapplicantfatherHusband;
    private javax.swing.JTextField tfapplicantmother;
    private javax.swing.JTextField tfapplicantname;
    private javax.swing.JTextField tfapplicantpermenantaddress;
    private javax.swing.JTextField tfapplicantpresentaddress;
    // End of variables declaration//GEN-END:variables
}
