/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package podmamanagement;

import com.sun.xml.internal.ws.api.streaming.XMLStreamReaderFactory;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author millat
 */
public class DebtCollection extends javax.swing.JFrame {

    /**
     * Creates new form DebtCollection
     */
    public DebtCollection() {
        initComponents();
       infoCollection();
      
       
       
           
        
    }
    
   public void infoCollection(){
       try{
           ClientID.setText(MyClient.id); 
           String id = MyClient.id;
           String myDriver = "org.gjt.mm.mysql.Driver";
           String myUrl = "jdbc:mysql://localhost:3306/RudoDatabase";
           Class.forName(myDriver);
           Connection conn = DriverManager.getConnection(myUrl,"test", "test");
           
           
           String Dquery = "select * from grouptablewithclientitems where Client_Id='"+MyClient.id+"'";
           PreparedStatement pred = conn.prepareStatement(Dquery);
           ResultSet rs = pred.executeQuery();
           
           while(rs.next()){
               Client_Name.setText(rs.getString("Client_Name"));
               TfTotalInstallment.setText(rs.getString("Number_Of_Installments"));
               Total = rs.getString("Number_Of_Installments");
           }
           
          
           
           //calling RemainingIstallment() function 
           RemainingInstallment();
  
           
       }catch(Exception e){
           System.err.println(e);
           
       }
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ClientID = new javax.swing.JLabel();
        Client_Name = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TfTotalInstallment = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        RemainingInstallment = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        TfAmountOfTaka = new javax.swing.JTextField();
        TodaypaymentInsNo = new javax.swing.JTextField();
        InstallmentButton = new javax.swing.JButton();
        bCancel = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ID :");

        jLabel2.setText("Name :");

        ClientID.setText("id");

        Client_Name.setText("Client Name ");

        jLabel5.setText("Total installment: ");

        TfTotalInstallment.setText("Total installment no");

        jLabel7.setText("Remaining  installment :");

        RemainingInstallment.setText("0");

        jLabel9.setText("Today payment installment no:");

        jLabel10.setText("Amount of Taka");

        TodaypaymentInsNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TodaypaymentInsNoActionPerformed(evt);
            }
        });

        InstallmentButton.setText("Done");
        InstallmentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InstallmentButtonActionPerformed(evt);
            }
        });

        bCancel.setText("Cancel");
        bCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelActionPerformed(evt);
            }
        });

        jLabel3.setText("Date :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(TodaypaymentInsNo, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel1)))
                        .addGap(100, 100, 100)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Client_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TfTotalInstallment)
                            .addComponent(ClientID, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel7))
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TfAmountOfTaka, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RemainingInstallment, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(107, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(InstallmentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(220, 220, 220))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ClientID, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Client_Name))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TfTotalInstallment))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(RemainingInstallment))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(TodaypaymentInsNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(TfAmountOfTaka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InstallmentButton)
                    .addComponent(bCancel))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InstallmentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InstallmentButtonActionPerformed
        // TODO add your handling code here:
        try{
            String myDriver = "org.gjt.mm.mysql.Driver";
            String myUrl = "jdbc:mysql://localhost:3306/RudoDatabase";
            Class.forName(myDriver);
            Connection conn = DriverManager.getConnection(myUrl,"test", "test");
            String query = "insert into InstallmentTable (ID,Client_Name,TotalInstallmentNo,"
                + "payInstallmentNO,AmountOfTaka,Date)"+"values(?,?,?,?,?,?)";
            PreparedStatement preparedStmnt = conn.prepareStatement(query);
            preparedStmnt.setString(1, ClientID.getText());
            preparedStmnt.setString(2,Client_Name.getText());
            preparedStmnt.setString(3, TfTotalInstallment.getText());
            preparedStmnt.setString(4,TodaypaymentInsNo.getText());
            preparedStmnt.setString(5,TfAmountOfTaka.getText());
            preparedStmnt.setString(6,DebtCollectionDatePicker.getDate().toString());
            preparedStmnt.execute();
            conn.close();
        }catch(Exception e){
            System.out.println(e);
        }
        close();
        
    }//GEN-LAST:event_InstallmentButtonActionPerformed

    private void TodaypaymentInsNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TodaypaymentInsNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TodaypaymentInsNoActionPerformed

    private void bCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelActionPerformed
        // TODO add your handling code here:
        close();
    }//GEN-LAST:event_bCancelActionPerformed

    public  void RemainingInstallment(){
        try{
            String myDriver = "org.gjt.mm.mysql.Driver";
            String myUrl = "jdbc:mysql://localhost:3306/RudoDatabase";
            Class.forName(myDriver);
            Connection conn = DriverManager.getConnection(myUrl,"test", "test");
            System.out.println("joy");
            String query="SELECT sum(`payInstallmentNO`) as total FROM `InstallmentTable` WHERE `ID` = '"+MyClient.id+"' ";
            PreparedStatement pred = conn.prepareStatement(query);
            ResultSet rs = pred.executeQuery();
            
            // calculation for remaining installment for the client to be paid          
            
                while(rs.next()){
                    int  count = Integer.parseInt(rs.getString("total"));
                    if(count==0){
                      RemainingInstallment.setText(Total);  
                        }
                    else{
                        System.out.println(count);
                        String remain = Integer.toString(Integer.parseInt(Total)-count);
                        if(Integer.parseInt(remain)<=0){
                            JOptionPane.showMessageDialog(null, "All Installment is paid !!!");
                        }
                        RemainingInstallment.setText(remain);
                        }
                }
            
        }catch(Exception e){
            
        }
    }
      
        public void close(){

            WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOS­ING);
            Toolkit.getDefaultToolkit().getSystemEve­ntQueue().postEvent(winClosingEvent);

        }
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DebtCollection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DebtCollection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DebtCollection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DebtCollection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DebtCollection().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ClientID;
    private javax.swing.JLabel Client_Name;
    private javax.swing.JButton InstallmentButton;
    private javax.swing.JLabel RemainingInstallment;
    private javax.swing.JTextField TfAmountOfTaka;
    private javax.swing.JLabel TfTotalInstallment;
    private javax.swing.JTextField TodaypaymentInsNo;
    private javax.swing.JButton bCancel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables

int count = 0;
int TotalInstallment ;
String Total;
}
