/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package podmamanagement;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author millat
 */
public class ForgetPasswordJFrame extends javax.swing.JFrame {

    /**
     * Creates new form ForgetPasswordJFrame
     */
    public ForgetPasswordJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FPAnswer3_textf = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        FPAnswer2_textf = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        FPAnswer1_textf = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        FPRecoverButton = new javax.swing.JButton();
        FPCancelButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        FPUserNametf = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Forget Password");

        jLabel9.setText("3. What is your teacher name ?");

        jLabel7.setText("2. What is your favourate uncle name ?");

        jLabel6.setText("1. What is your favourate fruit ?");

        jLabel5.setFont(new java.awt.Font("DejaVu Serif Condensed", 3, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(235, 26, 10));
        jLabel5.setText("Answer This Question ");

        FPRecoverButton.setText("Done");
        FPRecoverButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FPRecoverButtonActionPerformed(evt);
            }
        });

        FPCancelButton.setText("Cancel");
        FPCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FPCancelButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Username: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(FPRecoverButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(FPCancelButton))
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(FPAnswer3_textf, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel6)
                        .addComponent(FPUserNametf, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE))
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(FPAnswer1_textf, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(FPAnswer2_textf, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)))
                .addContainerGap(190, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FPUserNametf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 21, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(FPAnswer1_textf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FPAnswer2_textf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(FPAnswer3_textf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FPRecoverButton)
                    .addComponent(FPCancelButton))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FPRecoverButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FPRecoverButtonActionPerformed
        // TODO add your handling code here:
        try{
            
            String myDriver = "org.gjt.mm.mysql.Driver";
            String myUrl = "jdbc:mysql://localhost:3306/RudoDatabase";
            Class.forName(myDriver);
            Connection conn = DriverManager.getConnection(myUrl,"test", "test");
            String usrname = FPUserNametf.getText();
            String query = "select count(UserName) from SigninAndLoginTable where UserName = '"+usrname+"' ";
            PreparedStatement pred = conn.prepareStatement(query);
            ResultSet rs = pred.executeQuery();
            rs.next();
            int count = rs.getInt(1);
            if(count==1){
                System.out.println("millat vai");
                String Ans1 = FPAnswer1_textf.getText();
                String Ans2 = FPAnswer2_textf.getText();
                String Ans3 = FPAnswer3_textf.getText();
                
                String  forgetquery = "select * from SigninAndLoginTable where UserName = ? and Question1Answer = ? and Question2Answer = ? and Question3Answer = ? "; 
                pred = conn.prepareStatement(forgetquery);
                pred.setString(1, usrname);
                pred.setString(2, Ans1);
                pred.setString(3, Ans2);
                pred.setString(4, Ans3);
                ResultSet rse = pred.executeQuery();
                if(rse.next()){
                    String pass=null;
                    System.out.println("hoiche");
                    String passQuery  = "select * from SigninAndLoginTable where UserName = '"+ usrname +"'";
                    pred = conn.prepareStatement(passQuery);
                    ResultSet result = pred.executeQuery();
                    while(result.next()){
                        pass = result.getString("Password");
                        
                    }
                    JOptionPane.showConfirmDialog(null, "Your Password is : "+pass);
                    
                    
                }else{
                    JOptionPane.showConfirmDialog(null, "Wrong Answer !!! Answer should be same as "
                            + "inputed in time of signup. Try again.");
                }
                
                
            }else{
               // JOptionPane.showMessageDialog(null, "Wrong UserName", "Username is not found !!!! Try again !", );
                JOptionPane.showMessageDialog(null, "Username is not found !!!! Try again !");
            }
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_FPRecoverButtonActionPerformed

    private void FPCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FPCancelButtonActionPerformed
        // TODO add your handling code here:
        close();
    }//GEN-LAST:event_FPCancelButtonActionPerformed

    public void close(){

      WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOS­ING);
      Toolkit.getDefaultToolkit().getSystemEve­ntQueue().postEvent(winClosingEvent);

    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForgetPasswordJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForgetPasswordJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForgetPasswordJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForgetPasswordJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ForgetPasswordJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField FPAnswer1_textf;
    private javax.swing.JTextField FPAnswer2_textf;
    private javax.swing.JTextField FPAnswer3_textf;
    private javax.swing.JButton FPCancelButton;
    private javax.swing.JButton FPRecoverButton;
    private javax.swing.JTextField FPUserNametf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
