/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package podmamanagement;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;



/**
 *
 * @author millat
 */
public class UpdateGroupDetail extends javax.swing.JFrame {

    /**
     * Creates new form UpdateGroupDetail
     */
    public UpdateGroupDetail() {
        initComponents();
               
    }
   
            

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tfNewGroupName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        LCurrentGroupName = new javax.swing.JLabel();
        bUpdate = new javax.swing.JButton();
        bCancel = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        LMessage = new javax.swing.JLabel();
        LGrade = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Group Name(new):");

        jLabel3.setText("Current Informarion:");

        bUpdate.setText("Update");
        bUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bUpdateActionPerformed(evt);
            }
        });

        bCancel.setText("Cancel");
        bCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelActionPerformed(evt);
            }
        });

        jLabel4.setText("EDIT GROUP DETAILS");

        jLabel6.setText("Grade:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(106, 106, 106)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(bUpdate)
                                .addGap(40, 40, 40)
                                .addComponent(bCancel)
                                .addGap(74, 74, 74))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(302, 302, 302)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(LGrade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tfNewGroupName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(LCurrentGroupName, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LCurrentGroupName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(tfNewGroupName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(LMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(LGrade, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bUpdate)
                            .addComponent(bCancel))))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bUpdateActionPerformed
        try {
            String myDriver = "org.gjt.mm.mysql.Driver";
            String myUrl = "jdbc:mysql://localhost:3306/RudoDatabase";
            Class.forName(myDriver);
            
            Connection conn = DriverManager.getConnection(myUrl, "test","test");
            
            String uppGroupName = tfNewGroupName.getText();
            String currentName = LCurrentGroupName.getText();
             
            if(LGrade.getText().equals("A")){
                  //for duplicate name....
                String GroupNameCheck = tfNewGroupName.getText();
                //calling the method for checking for same group name....
               
                Group_Name_Check_In_Different_Grades();
              
                //changing name and size...
                //if no same name exists...
                if(countA == 0 && countB == 0 && countC == 0 && countD == 0){
                String UpdateQuery = "update gradea set Group_Name = '"+uppGroupName+"' where Group_Name = '"+currentName+"'";
                PreparedStatement preparedStmnt = conn.prepareStatement(UpdateQuery);
                preparedStmnt.execute();
                
                // this is for update the groupTableWithClientItem
                String upgrouptableWithClientItemsQ ="update grouptablewithclientitems set Group_Name = '"+uppGroupName+"' where Group_Name = '"+currentName+"'";
                PreparedStatement pred = conn.prepareStatement(upgrouptableWithClientItemsQ);
                pred.execute();
                
                
                LMessage.setText("Updated!..");
                ClearTextFields();               
                //conn.close();
                }
            }
            else if(LGrade.getText().equals("B")){
                  //for duplicate name....
                String GroupNameCheck = tfNewGroupName.getText();
                //calling the method for checking for same group name....
                Group_Name_Check_In_Different_Grades();
                
              
                //changing name and size...
                //if no same name exists...
                if(countA == 0 && countB == 0 && countC == 0 && countD == 0){
                String UpdateQuery = "update gradeb set Group_Name = '"+uppGroupName+"' where Group_Name = '"+currentName+"'";
                PreparedStatement preparedStmnt = conn.prepareStatement(UpdateQuery);
                preparedStmnt.execute();
                
                // this is for update the groupTableWithClientItem
                String upgrouptableWithClientItemsQ ="update grouptablewithclientitems set Group_Name = '"+uppGroupName+"' where Group_Name = '"+currentName+"'";
                PreparedStatement pred = conn.prepareStatement(upgrouptableWithClientItemsQ);
                pred.execute();
                
                
                LMessage.setText("Updated!..");
                ClearTextFields();                
                //conn.close();
                }
            }
            else if(LGrade.getText().equals("C")){
                 //for duplicate name....
                String GroupNameCheck = tfNewGroupName.getText();
                //calling the method for checking for same group name....
                Group_Name_Check_In_Different_Grades();
                
              
                //changing name and size...
                //if no same name exists...
                if(countA == 0 && countB == 0 && countC == 0 && countD == 0){
                String UpdateQuery = "update gradec set Group_Name = '"+uppGroupName+"' where Group_Name = '"+currentName+"'";
                PreparedStatement preparedStmnt = conn.prepareStatement(UpdateQuery);
                preparedStmnt.execute();
                
                // this is for update the groupTableWithClientItem
                String upgrouptableWithClientItemsQ ="update grouptablewithclientitems set Group_Name = '"+uppGroupName+"' where Group_Name = '"+currentName+"'";
                PreparedStatement pred = conn.prepareStatement(upgrouptableWithClientItemsQ);
                pred.execute();
                
                conn.close();
                
                LMessage.setText("Updated!..");
                ClearTextFields();
               
                }
            }
            else if(LGrade.getText().equals("D")){
                 //for duplicate name....
                String GroupNameCheck = tfNewGroupName.getText();
                //calling the method for checking for same group name....
                Group_Name_Check_In_Different_Grades();
                
              
                //changing name and size...
                //if no same name exists...
                if(countA == 0 && countB == 0 && countC == 0 && countD == 0){
                String UpdateQuery = "update graded set Group_Name = '"+uppGroupName+"' where Group_Name = '"+currentName+"'";
                PreparedStatement preparedStmnt = conn.prepareStatement(UpdateQuery);
                preparedStmnt.execute();
                
                // this is for update the groupTableWithClientItem
                String upgrouptableWithClientItemsQ ="update grouptablewithclientitems set Group_Name = '"+uppGroupName+"' where Group_Name = '"+currentName+"'";
                PreparedStatement pred = conn.prepareStatement(upgrouptableWithClientItemsQ);
                pred.execute();
                
                
                LMessage.setText("Updated!..");
                ClearTextFields();
                conn.close();
                }
                
               
             
            }
            
                
           
            
            
            JOptionPane.showMessageDialog(null, "Group Name updated,Refresh Group Table by changing grade!!");
            close();
            
            
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_bUpdateActionPerformed

    private void bCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelActionPerformed
       close();
    }//GEN-LAST:event_bCancelActionPerformed

    //importing the current group details...
    public void ShowCurrentInfo(String name, String size, String grade){
        LCurrentGroupName.setText(name);
        
        LGrade.setText(grade);
        
    
    }
    
    private void ClearTextFields(){
        tfNewGroupName.setText(null);
       
        LGrade.setText(null);
       
        LCurrentGroupName.setText(null);
        LMessage.setText(null);
    
    }
    
    private void Group_Name_Check_In_Different_Grades(){
        
        try{
                String myDriver = "org.gjt.mm.mysql.Driver";
                String myUrl = "jdbc:mysql://localhost:3306/RudoDatabase";
                Class.forName(myDriver);

                Connection conn = DriverManager.getConnection(myUrl, "test","test");

        
        
                String GroupNameCheck = tfNewGroupName.getText();
                String GroupNameQueryA = "select count(Group_Name) from gradea where Group_Name = '"+GroupNameCheck+"'";
                PreparedStatement CheckA = conn.prepareStatement(GroupNameQueryA);
                ResultSet resultA = CheckA.executeQuery();
                resultA.next();
                countA = resultA.getInt(1);
                System.out.println(countA);
                if(countA == 1){
                    LMessage.setText("Duplicate Group Name Found In Grade A!..");
                }else{
                    //checking in grade B
                    
                    String GroupNameQueryB = "select count(Group_Name) from gradeb where Group_Name = '"+GroupNameCheck+"'";
                    PreparedStatement CheckB = conn.prepareStatement(GroupNameQueryB);
                    ResultSet resultB = CheckB.executeQuery();
                    resultB.next();
                    countB = resultB.getInt(1);
                    System.out.println(countB);
                    if(countB == 1){
                        LMessage.setText("Duplicate Group Name Found In Grade B!..");
                    
                    
                    }else{
                        String GroupNameQueryC = "select count(Group_Name) from gradec where Group_Name = '"+GroupNameCheck+"'";
                        PreparedStatement CheckC = conn.prepareStatement(GroupNameQueryC);
                        ResultSet resultC = CheckC.executeQuery();
                        resultC.next();
                        countC = resultC.getInt(1);
                        System.out.println(countC);
                        if(countC == 1){
                            LMessage.setText("Duplicate Group Name Found In Grade C!..");

                        }else{
                            String GroupNameQueryD = "select count(Group_Name) from graded where Group_Name = '"+GroupNameCheck+"'";
                            PreparedStatement CheckD = conn.prepareStatement(GroupNameQueryD);
                            ResultSet resultD = CheckD.executeQuery();
                            resultD.next();
                            countD = resultD.getInt(1);
                            System.out.println(countD);
                            if(countD == 1){
                                LMessage.setText("Duplicate Group Name Found In Grade D!..");
                            }else{
                               countA = 0;
                               countB = 0;
                               countC = 0;
                               countD = 0;
                            }
                        }
                    }
                        
                }
        }catch(Exception e){
            System.out.println(e);
        
        
    
    }
                            
    
    }
    //closing the current window if  it is canlelled.....
    public void close(){

      WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOS­ING);
      Toolkit.getDefaultToolkit().getSystemEve­ntQueue().postEvent(winClosingEvent);

}

    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateGroupDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateGroupDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateGroupDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateGroupDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateGroupDetail().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LCurrentGroupName;
    private javax.swing.JLabel LGrade;
    private javax.swing.JLabel LMessage;
    private javax.swing.JButton bCancel;
    private javax.swing.JButton bUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField tfNewGroupName;
    // End of variables declaration//GEN-END:variables

    //group name check variables...
    int countA = 0;
    int countB = 0;
    int countC = 0;
    int countD = 0;
}
